name: PR Build Test

on:
  pull_request:
    branches: [main]

permissions:
  checks: write

env:
  VITE_SUPABASE_API_URL: ${{ vars.VITE_SUPABASE_API_URL }}
  VITE_SUPABASE_API_KEY: ${{ vars.VITE_SUPABASE_API_KEY }}
  SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        uses: ./.github/actions/build
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Annotate Lint
        uses: ./.github/actions/annotate-lint
      - name: Lint
        uses: ./.github/actions/lint
